# Generated by Django 2.2.24 on 2021-11-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211103_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='puntos',
            field=models.IntegerField(null=True),
        ),
    ]
